apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "loki-rule-operator.fullname" . }}
  namespace: {{ .Values.loki.rulesConfigMap.namespace | default .Release.Namespace }}
  labels: {{- include "loki-rule-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["create"]
  - apiGroups: [""]
    resourceNames:
      - {{ .Values.loki.rulesConfigMap.name }}
      - loki-rule-operator-leader-lock # this is the operator leader lock
    resources:
      - configmaps
    verbs: ["get", "update"]
